### PR TITLE
Minor changes to `set-goal`

### LINKED ISSUE #116: Set-Goal Command description incorrect
image

should be f/FREQUENCY instead.

### PR DESCRIPTION
**Pull request by lue97**
Fixes #116 and #118

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -149,14 +149,15 @@ public Person withMeetings(List<Event> meetings) {
...
+        System.out.println(meetings);
         if (meetings.isEmpty()) {
             // user has never met up with this person before
             return DateUtil.ZERO_DAY;
         }
 
         LocalDate latestMeetingDate = meetings.stream()
                 .map(Event::getDate)
-                .filter(x -> x.isBefore(beforeDate))
+                .filter(x -> x.isBefore(beforeDate.plusDays(1)))
```
Comment (ivantjh) [inline src/main/java/seedu/address/model/person/Person.java:160]: This is to account for the meeting added today? Write comment above saying that the `latestMeetingDate` includes `today`

File: src/main/java/seedu/address/model/person/Person.java [hunk 2]
```diff
@@ -149,14 +149,15 @@ public Person withMeetings(List<Event> meetings) {
      * Compute the next goal deadline using meetings before the {@code beforeDate}
      */
     public LocalDate getGoalDeadline(LocalDate beforeDate) {
+        System.out.println(meetings);
```
Comment (ivantjh) [inline src/main/java/seedu/address/model/person/Person.java]: Need remove

**Review by ivantjh — CHANGES_REQUESTED** [review]

**Review by ivantjh — APPROVED** [review]
lgtm!
