### PR TITLE
Fix leftover bugs

### LINKED ISSUE #156: [PE-D] Profile pictures that may have been moved/renamed/deleted from the data folder cause the app to delete ALL data
### What is the issue:

Deleting a profile picture from the data folder causes the app to wipe the entire friendlist.

### How to replicate:

1. Start with FriendDex with default data
2. Add profile photos for some contacts
3. Exit FriendDex
4. Delete the profile photo(s)
5. Run FriendDex again
6. Observe that all data has been wiped

### Expected behaviour
Warn the user of this behaviour, or start without the profile picture and inform the user that images may be missing

### Why this is an issue:
Profile photos are not a core part of the app's data. Wiping it due to missing or incorrect file paths causes all data to be lost which can be quite catastrophic. This could be even more of an issue if data is transferred between systems, and file paths use different separators etc.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: DrWala/ped#8

### LINKED ISSUE #252: Upcoming Events does not update when a person is deleted

### LINKED ISSUE #253: Sort Upcoming Events by their descriptions if they have the same date
IMAGE 2021-04-10 21:32:26

Look at 12 Dec

### PR DESCRIPTION
**Pull request by ivantjh**
Fix #253
Fix #252 
Fix #156 -> by adding note in UG

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -43,13 +43,15 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToDelete = lastShownList.get(targetIndex.getZeroBased());
         model.deletePerson(personToDelete);
 
+        model.updateFilteredPersonList();
+        model.updateUpcomingDates();
+
         // TODO: check current tab and only switch if user is on PersonDetailsTab
```
Comment (Assyarul) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java]: I think we should remove the TODO if it is no longer relevant.

**Review by Assyarul — APPROVED** [review]
lgtm with just one line to clean up
