### PR TITLE
Fix issue of allowing invalid birthdays in `edit` command

### LINKED ISSUE #255: Do not allow edits to birthdays if meetings and special dates fall before new birthday

### PR DESCRIPTION
**Pull request by lue97**
Fixes #255

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -90,6 +94,26 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
...
         List<SpecialDate> dates = personToEdit.getDates();
         List<Meeting> meetings = personToEdit.getMeetings();
+
+        Optional<Meeting> earliestMeeting = meetings.stream().min(Comparator.comparing(Meeting::getDate));
+        Optional<SpecialDate> earliestDate = dates.stream().min(Comparator.comparing(SpecialDate::getDate));
+
+        if (earliestMeeting.isPresent() && earliestMeeting.get().getDate().isAfter(updatedBirthday.getDate())) {
+            throw new IllegalValueException(String.format(
+                    Messages.MESSAGE_BIRTHDAY_CONSTRAINT,
+                    DateUtil.toUi(updatedBirthday.getDate()),
```
Comment (ivantjh) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Use `DateUtil.toErrorMessage(updatedBirthday.getDate())`, the format for this date will match user input

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -90,6 +94,26 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
...
+                    "meeting",
+                    DateUtil.toUi(earliestMeeting.get().getDate())));
```
Comment (ivantjh) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Same for here. Use `DateUtil.toErrorMessage(...)`

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 3]
```diff
@@ -90,6 +94,26 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
...
+        }
+
+        if (earliestDate.isPresent() && earliestDate.get().getDate().isAfter(updatedBirthday.getDate())) {
+            throw new IllegalValueException(String.format(
+                    Messages.MESSAGE_BIRTHDAY_CONSTRAINT,
+                    DateUtil.toUi(updatedBirthday.getDate()),
```
Comment (ivantjh) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Use `DateUtil.toErrorMessage(...)`

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 4]
```diff
@@ -90,6 +94,26 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
...
+                    "special date",
+                    DateUtil.toUi(earliestDate.get().getDate())));
```
Comment (ivantjh) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Use `DateUtil.toErrorMessage(...)`

**Review by ivantjh — APPROVED** [review]
lgtm!

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 5]
```diff
@@ -90,6 +94,26 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
         Picture picture = personToEdit.getPicture().orElse(null);
         List<SpecialDate> dates = personToEdit.getDates();
         List<Meeting> meetings = personToEdit.getMeetings();
+
+        Optional<Meeting> earliestMeeting = meetings.stream().min(Comparator.comparing(Meeting::getDate));
+        Optional<SpecialDate> earliestDate = dates.stream().min(Comparator.comparing(SpecialDate::getDate));
```
Comment (chesterhow) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Aren't meetings and dates already sorted on add? The comparison here might be unnecessary.

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 1 above)
Comment (lue97) [reply src/main/java/seedu/address/logic/commands/EditCommand.java:103]: A bit weird to say "Invalid date. Person is not yet born on %1$s!" when you are changing the birthday itself

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 5 above)
Comment (lue97) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: Oh good catch

Comment (ivantjh) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: Actually, Lin Lue's one was okay. If the json data that is read not sorted, the bug will occur again but harder to find now because it is dependent on the order of the dates/meetings in the json.

Comment (ivantjh) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: Actually nvm, the `specialDates` and `meetings` are already sorted in the `JsonAdaptedPerson`
