### PR TITLE
Fix bug with group when editing person name.

### LINKED ISSUE #132: App cannot start up after a person changes name
The people in groups are not updated when a person changes. Json data file still has the old person name -> app cannot find this person it reads from the json.

### PR DESCRIPTION
**Pull request by Assyarul**
Fixes #132

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ListCommand.java [hunk 1]
```diff
@@ -44,8 +44,7 @@ public CommandResult execute(Model model) throws CommandException {
 
             //this will cause the UI to select the group cell.
             model.setGroup(group.getName(), group);
-
-            model.updateFilteredPersonList(x -> group.getPersons().contains(x));
+            model.updateFilteredPersonList(x -> group.getPersonNames().contains(x.getName()));
```
Comment (ivantjh) [inline src/main/java/seedu/address/logic/commands/ListCommand.java]: nitpick: Use `p` in the lambda perhaps, much more related to `person` than `x`

File: src/main/java/seedu/address/model/ModelManager.java [hunk 2]
```diff
@@ -132,7 +131,7 @@ public void setPerson(Person target, Person editedPerson) {
     @Override
     public void addGroup(Group group) {
         addressBook.addGroup(group);
-        updateFilteredPersonList(x -> group.getPersons().contains(x));
+        updateFilteredPersonList(x -> group.getPersonNames().contains(x));
```
Comment (ivantjh) [inline src/main/java/seedu/address/model/ModelManager.java]: Same for here `p -> group.getPersonNames().contains(p)`

File: src/main/java/seedu/address/model/group/Group.java [hunk 3]
```diff
@@ -44,15 +44,27 @@ public Name getName() {
...
-    public Set<Person> getPersons() {
+    public Set<Name> getPersonNames() {
         return persons;
     }
 
     public void addPerson(Person p) {
-        persons.add(p);
+        persons.add(p.getName());
+    }
+    public void setPerson(Person personToEdit, Person editedPerson) {
```
Comment (ivantjh) [inline src/main/java/seedu/address/model/group/Group.java:55]: New line here

File: src/main/java/seedu/address/model/group/Group.java [hunk 4]
```diff
@@ -44,15 +44,27 @@ public Name getName() {
...
+        if (persons.contains(personToEdit.getName())) {
+            persons.remove(personToEdit.getName());
+            persons.add(editedPerson.getName());
+        }
+    }
+    public void setPersonName(Name personNameToEdit, Name editedPersonName) {
```
Comment (ivantjh) [inline src/main/java/seedu/address/model/group/Group.java:62]: New line here

File: src/main/java/seedu/address/model/group/GroupHashMap.java [hunk 5]
```diff
@@ -42,7 +42,12 @@ public void add(Group toAdd) {
         }
         internalMap.put(toAdd.getName(), toAdd);
     }
-
+    /**
+     * Replace given person name with new name in all groups.
+     */
+    public void replacePerson(Name personToReplace, Name newPersonName) {
+        internalMap.values().stream().forEach(x->x.setPersonName(personToReplace, newPersonName));
```
Comment (ivantjh) [inline src/main/java/seedu/address/model/group/GroupHashMap.java]: style: should have space before and after the `->`

**Review by ivantjh — APPROVED** [review]
Minor cosmetic errors. Good to bind `Name` to group instead of `Person`, less information is known about `Person` to `Group`!

lgtm!
