### PR TITLE
Fixes for bugs concerning goals and meetings

### LINKED ISSUE #150: [PE-D] Deadline for yearly goal is incorrect if a previous meeting is deleted
### What is the issue:

Deleting a previous meeting causes the goal field to display incorrect data

### How to replicate:

1. Start with FriendDex with default data
2. Create a yearly meeting goal for Alex (Index 1)
3. Add a meeting for 01-01-2021
4. Add a meeting for 01-01-2022
5. Delete the 01-01-2021 meeting
6. Observe that the deadline for the is stated as "Missed on 31 Dec 1971"

### Expected behaviour
The deadline for the goal should be 31 Dec 2022 or 1 Jan 2023

### Why this is an issue:
When a previous meeting is deleted, the goal should update accordingly.

### Screenshot
Issue is highlighted in red

### State of data file

```{
  "persons" : [ {
    "name" : "Alex Yeoh",
    "phone" : "87438807",
    "email" : "alexyeoh@example.com",
    "birthday" : "01-01-1998",
    "goal" : "YEARLY",
    "address" : "Blk 30 Geylang Street 29, #06-40",
    "picture" : null,
    "debt" : "0.0",
    "tagged" : [ "friends" ],
    "dates" : [ ],
    "meetings" : [ {
      "date" : "2022-01-01",
      "time" : "16:00:00",
      "description" : "New years again!"
    } ]
  }, {
    "name" : "Bernice Yu",
    "phone" : "99272758",
    "email" : "berniceyu@example.com",
    "birthday" : "01-02-1999",
    "goal" : "NONE",
    "address" : "Blk 30 Lorong 3 Serangoon Gardens, #07-18",
    "picture" : null,
    "debt" : "0.0",
    "tagged" : [ "colleagues", "friends" ],
    "dates" : [ ],
    "meetings" : [ ]
  }, {
    "name" : "Charlotte Oliveiro",
    "phone" : "93210283",
    "email" : "charlotte@example.com",
    "birthday" : "03-11-1979",
    "goal" : "NONE",
    "address" : "Blk 11 Ang Mo Kio Street 74, #11-04",
    "picture" : null,
    "debt" : "0.0",
    "tagged" : [ "neighbours" ],
    "dates" : [ ],
    "meetings" : [ ]
  }, {
    "name" : "David Li",
    "phone" : "91031282",
    "email" : "lidavid@example.com",
    "birthday" : "14-12-1998",
    "goal" : "NONE",
    "address" : "Blk 436 Serangoon Gardens Street 26, #16-43",
    "picture" : null,
    "debt" : "0.0",
    "tagged" : [ "family" ],
    "dates" : [ ],
    "meetings" : [ ]
  }, {
    "name" : "Irfan Ibrahim",
    "phone" : "92492021",
    "email" : "irfan@example.com",
    "birthday" : "12-12-1995",
    "goal" : "NONE",
    "address" : "Blk 47 Tampines Street 20, #17-35",
    "picture" : null,
    "debt" : "0.0",
    "tagged" : [ "classmates" ],
    "dates" : [ ],
    "meetings" : [ ]
  }, {
    "name" : "Roy Balakrishnan",
    "phone" : "92624417",
    "email" : "royb@example.com",
    "birthday" : "05-02-1998",
    "goal" : "NONE",
    "address" : "Blk 45 Aljunied Street 85, #11-31",
    "picture" : null,
    "debt" : "0.0",
    "tagged" : [ "colleagues" ],
    "dates" : [ ],
    "meetings" : [ ]
  } ],
  "groups" : [ ]
}```


<!--session: 1617429934695-f5d57f1e-5986-44e2-ab31-d20e9d0aba5c-->

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: DrWala/ped#2

### LINKED ISSUE #152: [PE-D] Meeting dates in the future are allowed
### What is the issue:

Meeting dates that have not happened yet are allowed

### How to replicate:

1. Start with FriendDex with default data
2. Create a yearly meeting goal for Alex (Index 1)
3. Add a meeting for 01-01-2022
5. Observe that the meeting is allowed to be entered

### Expected behaviour
The meeting should be blocked, or a limit on how far ahead I can add a meeting (e.g within the day) should be imposed.

### Why this is an issue:
If the app is designed to help you keep track of and maintain your relationships (as stated in the UG), then it should not allow me to create meetings that have not happened yet, it would allow me to "game the system". This limitation is not documented in the UG either.

### Screenshot

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: DrWala/ped#4

### LINKED ISSUE #165: [PE-D] Error message with invalid date when adding meeting shows format specifiers
### What is the issue:

Error message with invalid date when adding meeting shows format specifiers

### How to replicate:

1. Run the following command on the default data: `add-meeting 1 d/04-4-2021 t/1200 desc/lunch`
2. Observe that the error message includes `%1$s`

### Expected behaviour:
`%1$s` should not be shown

### Why this is an issue:
The format specifiers are not part of the error message and should not be displayed

### Screenshot

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: DrWala/ped#18

### LINKED ISSUE #168: [PE-D] Meetings should be listed in chronological order to
### What is the issue:

Meetings are listed in insertion order instead of chronological order

### How to replicate:

1. Launch FriendDex with default data
2. Run the following commands
- `add-meeting 1 d/01-04-2021 t/1500 desc/dance`
- `add-meeting 1 d/03-04-2021 t/1000 desc/brunch`
- `add-meeting 1 d/03-01-2021 t/1000 desc/new years gathering`
3. Observe that dates are not in chronological order

### Expected behaviour:
Dates should be in chronological order

### Why this is an issue:
To keep track of my meetings with friends and maintain my goal of how frequently I meet them, past meetings should be shown in chronological order so I know when my last meeting was.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: DrWala/ped#21

### PR DESCRIPTION
**Pull request by lue97**
Fixes #150 
Fixes #152 
Fixes #165 
Fixes #168

### CODE REVIEW

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
     public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The person index provided is invalid";
     public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
     public static final String MESSAGE_INVALID_ARGUMENT_FORMAT = "Invalid argument format! \n%1$s";
-    public static final String MESSAGE_INVALID_DATE_FORMAT = "Invalid date format! \n%1$s";
+    public static final String MESSAGE_INVALID_DATE_FORMAT = "Invalid date format! \n";
     public static final String MESSAGE_INVALID_TIME_FORMAT = "Invalid time format! \n%1$s";
```
Comment (chesterhow) [inline src/main/java/seedu/address/commons/core/Messages.java]: Is the `%1$s` not needed for invalid date? Should we also remove it then for invalid time?

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 2]
```diff
@@ -71,7 +71,8 @@ public PersonCard(Person person, int displayedIndex) {
             goalText = "No goal set for this person";
         } else {
             LocalDate deadline = person.getGoalDeadline(LocalDate.now());
-            if (deadline.getYear() == DateUtil.ZERO_DAY.getYear()) {
+            LocalDate zeroDay = DateUtil.ZERO_DAY;
+            if (deadline.equals(zeroDay)) {
```
Comment (chesterhow) [inline src/main/java/seedu/address/ui/PersonCard.java]: Probably no need for a new variable here. Perhaps just `deadline.equals(DateUtil.ZERO_DAY)`?

File: src/main/java/seedu/address/model/person/Streak.java [hunk 3]
```diff
@@ -37,7 +37,9 @@ public static Streak from(Goal goal, List<Event> meetings) {
                 .map(Event::getDate)
                 .sorted(LocalDate::compareTo)
                 .collect(Collectors.toList());
-
+        if (meetings.isEmpty()) {
+            return new Streak(0);
+        }
```
Comment (chesterhow) [inline src/main/java/seedu/address/model/person/Streak.java]: What does this part do? Will this display streaks for people with no meetings yet?

**Review by chesterhow — APPROVED** [review]
LGTM
