### PR TITLE
Fixes for uniqueness of Person

### LINKED ISSUE #115: NPE when starting application with invalid addressbook.jsonj
image

Null Pointer Exception when starting application with data file with missing fields.
image
Seems Like is ValidGoal is taking in a null value.

Should have defaulted to creating an empty Address Book instead.

### LINKED ISSUE #155: [PE-D] UG does not specify what makes a friend unique
### What is the issue:

UG does not state that friends are defined to be unique based on name

### How to replicate:

1. Navigate to `add` command: https://ay2021s2-cs2103t-w14-1.github.io/tp/UserGuide.html#adding-a-person--add
2. Observe that the criteria for what makes a friend unique is not stated

### Expected behaviour
Criteria for unique friends (Names are unique) should be stated.

### Why this is an issue:
Users may have many friends that have common names (e.g Justin Tan).

### What the UG shows

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DrWala/ped#7

### LINKED ISSUE #173: [PE-D] Some details of friend are not unique
The contact list contains friends that could potentially have the same email, phone number, and home address. Some of these details should be unique and it is impossible for them to be the same

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: internityz/ped#6

### LINKED ISSUE #176: [PE-D] Some details of Edit function should be unique
Edit function allows unique personal details to be duplicated. Perhaps this should not be allowed.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: internityz/ped#9

### LINKED ISSUE #177: [PE-D] Add invalid name
Able to add just a number for name of person

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: branzuelajohn/ped#1

### LINKED ISSUE #179: [PE-D] Name of person not case sensitive
Able to add same person with same details but only difference is the name is capitalised

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: branzuelajohn/ped#3

### LINKED ISSUE #190: [PE-D] Able to edit name of person to same name as another person but different case
No details provided.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: branzuelajohn/ped#14

### PR DESCRIPTION
**Pull request by ivantjh**
- `Person` will be checked for uniqueness solely on their name ignoring letter case
- `Group` will also be checked for uniqueness based on their names ignoring letter case
- Unintended side effect: for the `del-group` command, `del-group n/Close friends` and `del-group n/ClOse FrienDs` are the same commands
- Update UG for above cases
- Make reading from json file more robust and log more errors from it

Fixes #155
Fixes #173
Fixes #176
Fixes #177 -> it is ok for numbers to be names
Fixes #179
Fixes #190

Fixes #115 -> Block null values from json data file

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedPicture.java [hunk 1]
```diff
@@ -30,14 +35,27 @@ public JsonAdaptedPicture(Picture source) {
...
+        logger.warning(String.format(MESSAGE_DESERIALIZE_ERROR_DUMP_DATA, "Picture}"));
+        logger.warning(this.toString());
+        return new IllegalValueException(message);
+    }
+
     /**
      * Converts this Jackson-friendly adapted picture object into the model's {@code Picture} object.
      */
     public Picture toModelType() throws IllegalValueException {
         if (!Picture.isValidFilePath(filePath)) {
```
Comment (lue97) [inline src/main/java/seedu/address/storage/JsonAdaptedPicture.java:48]: I think we can rename `Picture#isValidFilePath` to `isValid` or something since it checks more than just the path

**Review by lue97 — APPROVED** [review]
lgtm!

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java [hunk 2]
```diff
@@ -104,6 +107,12 @@ public JsonAdaptedPerson(Person source) {
                 .collect(Collectors.toList()));
     }
 
+    private IllegalValueException internalIllegalValueException(String message) {
+        logger.warning(String.format(MESSAGE_DESERIALIZE_ERROR_DUMP_DATA, "Person"));
+        logger.warning(this.toString());
+        return new IllegalValueException(message);
+    }
```
Comment (chesterhow) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:114]: This `internalIllegalValueException` seems to be used in quite a few places. Can we abstract this exception out?

**Review by chesterhow — APPROVED** [review]
LGTM, just a minor nit

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java (hunk 2 above)
Comment (ivantjh) [reply src/main/java/seedu/address/storage/JsonAdaptedPerson.java:114]: Quite hard to abstract this method because of circular dependencies. I am using `this.toString()` in this method. 

Lets say if I create something like this to abstract:
```java
/**
 * This factory allows the creation of IllegalValueExceptions with inbuilt logging. We assume that everytime
 * a class uses this factory to create an exception, that exception will be thrown and so we log. This factory
 * should only be used for throwing IllegalValueExceptions for errors found during json deserialization.
 */
public class JsonExceptionFactory {
    private final Logger logger;
    private final String clazzName;
    private final Object object;

    public <T> JsonExceptionFactory(Class<T> clazz, String clazzToDeserialize, Object objectToDump) {
        logger = LogsCenter.getLogger(clazz);
        clazzName = clazzToDeserialize;
        object = objectToDump;
    }

    public IllegalValueException build(String message) {
        logger.warning(String.format(MESSAGE_DESERIALIZE_ERROR_DUMP_DATA, clazzName));
        logger.warning(object.toString());
        return new IllegalValueException(message);
    }
}
```

In `JsonAdaptedPerson.java`:
```java
// ...
private final JsonExceptionFactory exceptionFactory = new
            JsonExceptionFactory(JsonAdaptedPerson.class, "Person", this);
// ...
throw exceptionFactory.build(String.format(MISSING_FIELD_MESSAGE_FORMAT,
                    Name.class.getSimpleName()));
```

Will have circular dependency because `JsonAdaptedPerson` owns `JsonExceptionFactory` owns `JsonAdaptedPerson`, to put it simply `JsonAdaptedPerson` -> `JsonExceptionFactory` -> `JsonAdaptedPerson`

Comment (ivantjh) [reply src/main/java/seedu/address/storage/JsonAdaptedPerson.java:114]: Will further consider abstracting it out if it becomes easier.
